const motorActionTypes = {
  FETCH_MOTORCYCLES_START: 'FETCH_MOTORCYCLES_START',
  FETCH_MOTORCYCLES_SUCCESS: 'FETCH_MOTORCYCLES_SUCCESS',
  FETCH_MOTORCYCLES_ERROR: 'FETCH_MOTORCYCLES_ERROR',
  FETCH_MOTORCYCLE_START: 'FETCH_MOTORCYCLE_START',
  FETCH_MOTORCYCLE_SUCCESS: 'FETCH_MOTORCYCLE_SUCCESS',
  FETCH_MOTORCYCLE_ERROR: 'FETCH_MOTORCYCLE_ERROR',
};

export default motorActionTypes;
