const motorActionTypes = {
  FETCH_MOTORCYCLES_START: 'FETCH_MOTORCYCLES_START',
  FETCH_MOTORCYCLES_SUCCESS: 'FETCH_MOTORCYCLES_SUCCESS',
  FETCH_MOTORCYCLES_ERROR: 'FETCH_MOTORCYCLES_ERROR',

};

export default motorActionTypes;
