const ReservationActionType = {
  FETCH_RESERVATIONS_START: 'FETCH_RESERVATIONS_START',
  FETCH_RESERVATIONS_SUCCESS: 'FETCH_RESERVATIONS_SUCCESS',
  FETCH_RESERVATIONS_ERROR: 'FETCH_RESERVATIONS_ERROR',
  FETCH_RESERVATION_START: 'FETCH_RESERVATION_START',
  FETCH_RESERVATION_SUCCESS: 'FETCH_RESERVATION_SUCCESS',
  FETCH_RESERVATION_ERROR: 'FETCH_RESERVATION_ERROR',
};

export default ReservationActionType;
